export const ACKS = {
  statusEffects: [
    {
      acks: true,
      id: "surprised",
      name: "Surprised",
      img: "systems/acks/assets/icons/surprised.svg",
      duration: { rounds: 1 },
    },
    { acks: true, id: "overnumbering", name: "OverNumbered", img: "icons/svg/regen.svg" },
    { acks: true, id: "done", name: "Done", img: "icons/svg/cancel.svg" },
    { acks: true, id: "readied", name: "Readied", img: "icons/svg/ice-aura.svg" },
    { acks: true, id: "delayed", name: "Delayed", img: "icons/svg/clockwork.svg" },
    { acks: true, id: "slumbering", name: "Slumbering", img: "icons/svg/stoned.svg" },
  ],
  scores: {
    str: "ACKS.scores.str.long",
    int: "ACKS.scores.int.long",
    wis: "ACKS.scores.wis.long",
    dex: "ACKS.scores.dex.long",
    con: "ACKS.scores.con.long",
    cha: "ACKS.scores.cha.long",
  },
  roll_type: {
    result: "=",
    above: "≥",
    below: "≤",
  },
  saves_short: {
    death: "ACKS.saves.death.short",
    wand: "ACKS.saves.wand.short",
    paralysis: "ACKS.saves.paralysis.short",
    breath: "ACKS.saves.breath.short",
    spell: "ACKS.saves.spell.short",
  },
  saves_long: {
    death: "ACKS.saves.death.long",
    wand: "ACKS.saves.wand.long",
    paralysis: "ACKS.saves.paralysis.long",
    breath: "ACKS.saves.breath.long",
    spell: "ACKS.saves.spell.long",
  },
  armor: {
    unarmored: "ACKS.armor.unarmored",
    veryLight: "ACKS.armor.veryLight",
    light: "ACKS.armor.light",
    medium: "ACKS.armor.medium",
    heavy: "ACKS.armor.heavy",
    shield: "ACKS.armor.shield",
  },
  colors: {
    green: "ACKS.colors.green",
    red: "ACKS.colors.red",
    yellow: "ACKS.colors.yellow",
    purple: "ACKS.colors.purple",
    blue: "ACKS.colors.blue",
    orange: "ACKS.colors.orange",
    white: "ACKS.colors.white",
  },
  proficiencyType: {
    general: "ACKS.proficiencyType.general",
    class: "ACKS.proficiencyType.class",
  },
  // will be auto localized during setup hook
  tags: {
    melee: "ACKS.items.Melee",
    missile: "ACKS.items.Missile",
    slow: "ACKS.items.Slow",
    twohanded: "ACKS.items.TwoHanded",
    blunt: "ACKS.items.Blunt",
    brace: "ACKS.items.Brace",
    splash: "ACKS.items.Splash",
    reload: "ACKS.items.Reload",
    charge: "ACKS.items.Charge",
  },
  tag_icons: {
    melee: "fa-solid fa-swords",
    missile: "fa-solid fa-bow-arrow",
    slow: "fa-solid fa-hourglass",
    twohanded: "fa-solid fa-hand-holding-hand",
    blunt: "fa-solid fa-hammer-war",
    brace: "fa-solid fa-slash",
    splash: "fa-solid fa-burst",
    reload: "fa-solid fa-repeat",
    charge: "fa-solid fa-person-running-fast",
  },
  tag_images: {
    melee: "systems/acks/assets/melee.png",
    missile: "systems/acks/assets/missile.png",
    slow: "systems/acks/assets/slow.png",
    twohanded: "systems/acks/assets/twohanded.png",
    blunt: "systems/acks/assets/blunt.png",
    brace: "systems/acks/assets/brace.png",
    splash: "systems/acks/assets/splash.png",
    reload: "systems/acks/assets/reload.png",
    charge: "systems/acks/assets/charge.png",
  },
  hireling_categories: {
    henchman: "ACKS.hireling.henchman",
    mercenary: "ACKS.hireling.mercenary",
    specialist: "ACKS.hireling.specialist",
  },
  item_subtypes: {
    item: "ACKS.items.item",
    clothing: "ACKS.items.clothing",
  },
  monster_saves: {
    0: {
      label: "Normal Human",
      d: 15,
      w: 17,
      p: 14,
      b: 16,
      s: 18,
    },
    1: {
      label: "1",
      d: 14,
      w: 16,
      p: 13,
      b: 15,
      s: 17,
    },
    2: {
      label: "2-3",
      d: 13,
      w: 15,
      p: 12,
      b: 14,
      s: 16,
    },
    4: {
      label: "4",
      d: 12,
      w: 14,
      p: 11,
      b: 13,
      s: 15,
    },
    5: {
      label: "5-6",
      d: 11,
      w: 13,
      p: 10,
      b: 12,
      s: 14,
    },
    7: {
      label: "7",
      d: 10,
      w: 12,
      p: 9,
      b: 11,
      s: 13,
    },
    8: {
      label: "8-9",
      d: 9,
      w: 11,
      p: 8,
      b: 10,
      s: 12,
    },
    10: {
      label: "10",
      d: 8,
      w: 10,
      p: 7,
      b: 9,
      s: 11,
    },
    11: {
      label: "11-12",
      d: 7,
      w: 9,
      p: 6,
      b: 8,
      s: 10,
    },
    13: {
      label: "13",
      d: 6,
      w: 8,
      p: 5,
      b: 7,
      s: 9,
    },
    14: {
      label: "14+",
      d: 5,
      w: 7,
      p: 4,
      b: 6,
      s: 8,
    },
  },
  base_speed: {
    unencumbered: 120,
    low_encumbrance: 90,
    mid_encumbrance: 60,
    high_encumbrance: 30,
    overburdened: 0,
  },
};
